# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

networks:
  default: development
  development:
    cmd_settings:
      mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar

# enable output of development artifacts to load with react
dev_deployment_artifacts: true

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"